name: Build pelican based resume and push it to GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install additional packages
      run: |
        sudo apt install python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
    - name: Install Pips
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install python dependencies
      run: pipenv install --system --deploy --ignore-pipfile
    - name: Build resume and deploy
      uses: ./.github/actions/build-and-deploy